services:
  whale-panel:
    image: primezdev/whale-panel:latest
    container_name: whale-panel
    restart: always
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    env_file:
      - ./.env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"